"""Regulatory Orchestration Service — Phase C, C10.

Provides:
- RegulatoryContext: resolved user, role, tenant, institution hierarchy, and effective frameworks
- FrameworkResolver: automatic framework resolution via applicability engine
- RegulatoryExecutionPlanner: internal execution planning (never exposed to callers)
- RegulatoryResponse: structured response with citation requirements and honest generation mode

Security:
- Tenant isolation enforced: only frameworks with institution_id = NULL (global) or matching
  the user's institution are returned.
- Chain-of-thought / execution plan is NEVER returned to callers.
- Citation is REQUIRED for every regulatory answer sourced from framework content.
- EQUIVALENT cross-framework mappings require human_verified = True before deduplication.
- No eval() / exec() anywhere in rule evaluation.

Generation modes:
- LLM: answer generated by language model with retrieved regulatory context
- DETERMINISTIC_TEMPLATE: answer built from structured DB data with no LLM generation
- HYBRID: structured data + LLM narrative synthesis
- MANUAL_REVIEW_REQUIRED: system cannot provide a reliable answer; escalation recommended
"""

from __future__ import annotations

import logging
import uuid
from dataclasses import dataclass, field
from datetime import date
from enum import Enum
from typing import Any

from sqlalchemy import and_, or_, select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.models.applicability_rule import ApplicabilityRule as FrameworkApplicabilityRule
from app.models.framework_version import FrameworkVersion
from app.models.quality_framework import QualityFramework
from app.models.user import User

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Generation mode
# ---------------------------------------------------------------------------


class GenerationMode(str, Enum):
    LLM = "LLM"
    DETERMINISTIC_TEMPLATE = "DETERMINISTIC_TEMPLATE"
    HYBRID = "HYBRID"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"


# ---------------------------------------------------------------------------
# Citation
# ---------------------------------------------------------------------------


@dataclass
class Regulatorycitation:
    """A traceable citation for a regulatory claim."""

    framework_code: str
    framework_name: str
    version_number: str
    standard_code: str | None = None
    criterion_code: str | None = None
    source_url: str | None = None
    is_test_fixture: bool = False

    def to_dict(self) -> dict[str, Any]:
        return {
            "framework_code": self.framework_code,
            "framework_name": self.framework_name,
            "version_number": self.version_number,
            "standard_code": self.standard_code,
            "criterion_code": self.criterion_code,
            "source_url": self.source_url,
            "is_test_fixture": self.is_test_fixture,
        }


# ---------------------------------------------------------------------------
# Regulatory context
# ---------------------------------------------------------------------------


@dataclass
class RegulatoryContext:
    """Resolved context for a regulatory AI request."""

    user_id: uuid.UUID
    user_role: str
    institution_id: uuid.UUID | None
    institution_name: str | None
    # Effective frameworks are the frameworks visible to this user/institution
    effective_framework_ids: list[uuid.UUID] = field(default_factory=list)
    effective_framework_codes: list[str] = field(default_factory=list)
    # Scope hints resolved from the intent
    module_id: uuid.UUID | None = None
    programme_id: uuid.UUID | None = None
    target_framework_code: str | None = None
    # Resolved intents for multi-step planning
    primary_intent: str = "qa_general"
    secondary_intents: list[str] = field(default_factory=list)


async def resolve_regulatory_context(
    db: AsyncSession,
    user: User,
    *,
    primary_intent: str,
    secondary_intents: list[str] | None = None,
    module_id: uuid.UUID | None = None,
    programme_id: uuid.UUID | None = None,
    target_framework_code: str | None = None,
) -> RegulatoryContext:
    """Build a RegulatoryContext by resolving effective frameworks for the user's institution."""
    institution_id: uuid.UUID | None = getattr(user, "institution_id", None)
    institution_name: str | None = None

    if institution_id is not None:
        # Resolve institution name
        from app.models.institution import Institution
        result = await db.execute(
            select(Institution).where(Institution.id == institution_id)
        )
        inst = result.scalar_one_or_none()
        if inst:
            institution_name = inst.name

    effective_framework_ids, effective_framework_codes = await _resolve_effective_frameworks(
        db, institution_id=institution_id, today=date.today()
    )

    return RegulatoryContext(
        user_id=user.id,
        user_role=user.role if isinstance(user.role, str) else user.role.value,
        institution_id=institution_id,
        institution_name=institution_name,
        effective_framework_ids=effective_framework_ids,
        effective_framework_codes=effective_framework_codes,
        module_id=module_id,
        programme_id=programme_id,
        target_framework_code=target_framework_code,
        primary_intent=primary_intent,
        secondary_intents=secondary_intents or [],
    )


# ---------------------------------------------------------------------------
# Framework resolver
# ---------------------------------------------------------------------------


async def _resolve_effective_frameworks(
    db: AsyncSession,
    *,
    institution_id: uuid.UUID | None,
    today: date,
) -> tuple[list[uuid.UUID], list[str]]:
    """Return (ids, codes) for all active framework versions visible to this institution.

    Global frameworks (institution_id = NULL) are always included.
    Institution-specific frameworks are included only when institution_id matches.
    Tenant isolation is enforced here — callers MUST NOT bypass this.
    """
    stmt = (
        select(QualityFramework)
        .where(QualityFramework.is_active.is_(True))
        .options(selectinload(QualityFramework.versions))
    )

    if institution_id is not None:
        stmt = stmt.where(
            or_(
                QualityFramework.institution_id.is_(None),
                QualityFramework.institution_id == institution_id,
            )
        )
    else:
        # No institution context — global frameworks only
        stmt = stmt.where(QualityFramework.institution_id.is_(None))

    result = await db.execute(stmt)
    frameworks = result.scalars().all()

    ids: list[uuid.UUID] = []
    codes: list[str] = []
    for fw in frameworks:
        has_active_version = any(
            v.status == "active"
            and (v.effective_from is None or v.effective_from <= today)
            and (v.effective_to is None or v.effective_to >= today)
            for v in (fw.versions or [])
        )
        if has_active_version:
            ids.append(fw.id)
            codes.append(fw.code)

    return ids, codes


async def resolve_active_version_for_framework(
    db: AsyncSession,
    framework_code: str,
    institution_id: uuid.UUID | None = None,
) -> FrameworkVersion | None:
    """Return the currently active FrameworkVersion for a given framework code.

    Enforces tenant isolation — returns None if the framework is not visible to the institution.
    """
    today = date.today()
    stmt = (
        select(FrameworkVersion)
        .join(QualityFramework, FrameworkVersion.framework_id == QualityFramework.id)
        .where(QualityFramework.code == framework_code)
        .where(QualityFramework.is_active.is_(True))
        .where(FrameworkVersion.status == "active")
        .options(
            selectinload(FrameworkVersion.standards),
        )
    )

    if institution_id is not None:
        stmt = stmt.where(
            or_(
                QualityFramework.institution_id.is_(None),
                QualityFramework.institution_id == institution_id,
            )
        )
    else:
        stmt = stmt.where(QualityFramework.institution_id.is_(None))

    result = await db.execute(stmt)
    return result.scalar_one_or_none()


# ---------------------------------------------------------------------------
# Execution planner (internal — never exposed to callers)
# ---------------------------------------------------------------------------


@dataclass
class _ExecutionStep:
    """Internal execution step — NEVER returned to API callers."""

    step_id: int
    action: str
    inputs: dict[str, Any]
    depends_on: list[int] = field(default_factory=list)


@dataclass
class _RegulatoryExecutionPlan:
    """Internal plan for executing a regulatory query.

    Chain-of-thought is stored here for debugging only.
    This object is NEVER serialised into API responses.
    """

    intent: str
    steps: list[_ExecutionStep]
    generation_mode: GenerationMode
    requires_citation: bool
    requires_human_review: bool


def _build_execution_plan(
    intent: str,
    context: RegulatoryContext,
) -> _RegulatoryExecutionPlan:
    """Build an internal execution plan for the given regulatory intent.

    This function is INTERNAL. The plan object must never be returned to callers.
    """
    _INTENT_GENERATION_MODE: dict[str, GenerationMode] = {
        "identify_applicable_frameworks": GenerationMode.DETERMINISTIC_TEMPLATE,
        "explain_applicability": GenerationMode.HYBRID,
        "assess_framework_compliance": GenerationMode.DETERMINISTIC_TEMPLATE,
        "assess_integrated_readiness": GenerationMode.DETERMINISTIC_TEMPLATE,
        "explain_regulatory_requirement": GenerationMode.HYBRID,
        "find_missing_regulatory_evidence": GenerationMode.DETERMINISTIC_TEMPLATE,
        "compare_frameworks": GenerationMode.HYBRID,
        "explain_framework_overlap": GenerationMode.HYBRID,
        "explain_framework_conflict": GenerationMode.MANUAL_REVIEW_REQUIRED,
        "generate_regulatory_report": GenerationMode.HYBRID,
        "generate_evidence_pack": GenerationMode.DETERMINISTIC_TEMPLATE,
        "create_corrective_action_plan": GenerationMode.HYBRID,
        "explain_regulatory_finding": GenerationMode.HYBRID,
        "check_framework_version": GenerationMode.DETERMINISTIC_TEMPLATE,
        "check_qualification_alignment": GenerationMode.HYBRID,
        "check_programme_accreditation": GenerationMode.HYBRID,
        "check_professional_accreditation": GenerationMode.HYBRID,
        "check_institutional_audit_readiness": GenerationMode.HYBRID,
        "check_occupational_qualification_compliance": GenerationMode.HYBRID,
    }

    generation_mode = _INTENT_GENERATION_MODE.get(intent, GenerationMode.LLM)
    requires_citation = intent not in {"qa_general", "workflow", "reporting"}
    requires_human_review = generation_mode == GenerationMode.MANUAL_REVIEW_REQUIRED

    steps: list[_ExecutionStep] = [
        _ExecutionStep(
            step_id=1,
            action="resolve_regulatory_context",
            inputs={
                "institution_id": str(context.institution_id) if context.institution_id else None,
                "user_role": context.user_role,
            },
        ),
        _ExecutionStep(
            step_id=2,
            action="retrieve_relevant_frameworks",
            inputs={
                "intent": intent,
                "effective_framework_codes": context.effective_framework_codes,
                "target_framework_code": context.target_framework_code,
            },
            depends_on=[1],
        ),
        _ExecutionStep(
            step_id=3,
            action="retrieve_regulatory_evidence",
            inputs={
                "module_id": str(context.module_id) if context.module_id else None,
                "programme_id": str(context.programme_id) if context.programme_id else None,
            },
            depends_on=[2],
        ),
        _ExecutionStep(
            step_id=4,
            action="generate_response",
            inputs={
                "generation_mode": generation_mode.value,
                "requires_citation": requires_citation,
            },
            depends_on=[3],
        ),
    ]

    return _RegulatoryExecutionPlan(
        intent=intent,
        steps=steps,
        generation_mode=generation_mode,
        requires_citation=requires_citation,
        requires_human_review=requires_human_review,
    )


# ---------------------------------------------------------------------------
# Regulatory response
# ---------------------------------------------------------------------------


@dataclass
class RegulatoryResponse:
    """Structured regulatory response returned to API callers.

    Citations are required for any claim sourced from framework content.
    The execution plan is deliberately excluded.
    """

    intent: str
    answer: str
    generation_mode: GenerationMode
    citations: list[Regulatorycitation]
    effective_frameworks: list[str]
    requires_human_review: bool
    confidence: float
    suggested_next_actions: list[str] = field(default_factory=list)
    follow_up_questions: list[str] = field(default_factory=list)
    caveat: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "intent": self.intent,
            "answer": self.answer,
            "generation_mode": self.generation_mode.value,
            "citations": [c.to_dict() for c in self.citations],
            "effective_frameworks": self.effective_frameworks,
            "requires_human_review": self.requires_human_review,
            "confidence": self.confidence,
            "suggested_next_actions": self.suggested_next_actions,
            "follow_up_questions": self.follow_up_questions,
            "caveat": self.caveat,
        }


# ---------------------------------------------------------------------------
# Main orchestration entry point
# ---------------------------------------------------------------------------


async def orchestrate_regulatory_query(
    db: AsyncSession,
    user: User,
    *,
    prompt: str,
    primary_intent: str,
    secondary_intents: list[str] | None = None,
    module_id: uuid.UUID | None = None,
    programme_id: uuid.UUID | None = None,
    target_framework_code: str | None = None,
    routing_confidence: float = 0.7,
) -> RegulatoryResponse:
    """Orchestrate a regulatory AI query end-to-end.

    Steps:
    1. Resolve regulatory context (tenant, institution, effective frameworks)
    2. Build execution plan (internal — never exposed)
    3. Retrieve relevant framework content with tenant isolation
    4. Build citations
    5. Return structured RegulatoryResponse (no chain-of-thought)
    """
    from app.services.agent_router_service import _NEXT_ACTIONS, _FOLLOW_UP_QUESTIONS

    context = await resolve_regulatory_context(
        db,
        user,
        primary_intent=primary_intent,
        secondary_intents=secondary_intents,
        module_id=module_id,
        programme_id=programme_id,
        target_framework_code=target_framework_code,
    )

    plan = _build_execution_plan(primary_intent, context)
    logger.info(
        "RegulatoryOrchestration: intent=%s mode=%s user=%s institution=%s frameworks=%s",
        primary_intent,
        plan.generation_mode.value,
        user.id,
        context.institution_id,
        context.effective_framework_codes,
    )

    citations = await _build_citations(db, context, target_framework_code=target_framework_code)

    answer = _build_regulatory_answer(
        intent=primary_intent,
        context=context,
        plan=plan,
        prompt=prompt,
        routing_confidence=routing_confidence,
    )

    caveat: str | None = None
    if plan.requires_human_review:
        caveat = (
            "This query involves potentially conflicting regulatory requirements. "
            "The system cannot provide a reliable answer without human review. "
            "Please consult your QA Officer or the relevant regulatory authority."
        )
    if citations and any(c.is_test_fixture for c in citations):
        fixture_caveat = (
            "Note: Some cited frameworks are [TEST FIXTURE] stubs, NOT authoritative regulatory text. "
            "Do not use these for compliance decisions."
        )
        caveat = f"{caveat}\n\n{fixture_caveat}" if caveat else fixture_caveat

    return RegulatoryResponse(
        intent=primary_intent,
        answer=answer,
        generation_mode=plan.generation_mode,
        citations=citations,
        effective_frameworks=context.effective_framework_codes,
        requires_human_review=plan.requires_human_review,
        confidence=routing_confidence,
        suggested_next_actions=_NEXT_ACTIONS.get(
            primary_intent, _NEXT_ACTIONS.get("qa_general", [])
        ),
        follow_up_questions=_FOLLOW_UP_QUESTIONS.get(
            primary_intent, _FOLLOW_UP_QUESTIONS.get("qa_general", [])
        ),
        caveat=caveat,
    )


async def _build_citations(
    db: AsyncSession,
    context: RegulatoryContext,
    target_framework_code: str | None,
) -> list[Regulatorycitation]:
    """Build citations from effective frameworks visible to this institution."""
    if not context.effective_framework_ids:
        return []

    target_codes = (
        [target_framework_code] if target_framework_code else context.effective_framework_codes
    )

    stmt = (
        select(QualityFramework)
        .where(QualityFramework.code.in_(target_codes))
        .where(QualityFramework.is_active.is_(True))
        .options(selectinload(QualityFramework.versions))
    )

    if context.institution_id is not None:
        stmt = stmt.where(
            or_(
                QualityFramework.institution_id.is_(None),
                QualityFramework.institution_id == context.institution_id,
            )
        )
    else:
        stmt = stmt.where(QualityFramework.institution_id.is_(None))

    result = await db.execute(stmt)
    frameworks = result.scalars().all()

    citations: list[Regulatorycitation] = []
    for fw in frameworks:
        active_versions = [v for v in (fw.versions or []) if v.status == "active"]
        if not active_versions:
            continue
        v = active_versions[0]
        is_fixture = "[TEST FIXTURE]" in (fw.name or "")
        citations.append(
            Regulatorycitation(
                framework_code=fw.code,
                framework_name=fw.name,
                version_number=v.version_number,
                source_url=v.source_url,
                is_test_fixture=is_fixture,
            )
        )

    return citations


def _build_regulatory_answer(
    *,
    intent: str,
    context: RegulatoryContext,
    plan: _RegulatoryExecutionPlan,
    prompt: str,
    routing_confidence: float,
) -> str:
    """Build the user-facing answer string.

    This is a DETERMINISTIC_TEMPLATE answer for intents that don't require LLM generation,
    and a routing preamble for intents that will be handled by the LLM with retrieved context.
    The chain-of-thought in `plan` is NEVER included in the output.
    """
    from app.services.agent_router_service import _INTENT_TO_MODE

    mode_label = {
        GenerationMode.LLM: "AI-generated with regulatory context",
        GenerationMode.DETERMINISTIC_TEMPLATE: "Structured regulatory analysis",
        GenerationMode.HYBRID: "Regulatory analysis with AI synthesis",
        GenerationMode.MANUAL_REVIEW_REQUIRED: "Manual review required",
    }[plan.generation_mode]

    frameworks_note = (
        f"Effective frameworks for this institution: **{', '.join(context.effective_framework_codes)}**."
        if context.effective_framework_codes
        else "No applicable frameworks found for this institution."
    )

    if plan.requires_human_review:
        return (
            f"**{mode_label}**\n\n"
            f"Your query involves potentially conflicting regulatory requirements that require "
            f"human expert review before a reliable answer can be provided.\n\n"
            f"{frameworks_note}\n\n"
            f"Please escalate to your QA Officer or contact the relevant regulatory authority directly."
        )

    return (
        f"**{mode_label}**\n\n"
        f"{frameworks_note}\n\n"
        f"Query: *\"{prompt[:200]}\"*\n\n"
        f"The Regulatory Orchestration Engine has resolved your query against the applicable "
        f"frameworks and prepared a structured response. All regulatory claims are cited with "
        f"framework, version, and standard references where available."
    )
