"""add_knowledge_review_tables

Revision ID: b0df78d4b8ec
Revises: 7c5db84357e3
Create Date: 2026-07-01 10:00:00.647600+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0df78d4b8ec'
down_revision: Union[str, None] = '7c5db84357e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_review_batches',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('batch_name', sa.String(length=255), nullable=False),
    sa.Column('ikp_version', sa.String(length=20), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('faculty_scope', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_extraction_path', sa.Text(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('approved_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('pending_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('export_path', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_review_batches_institution_id'), 'knowledge_review_batches', ['institution_id'], unique=False)
    op.create_table('knowledge_review_items',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.String(length=255), nullable=True),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_key', sa.String(length=255), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('extracted_value', sa.Text(), nullable=False),
    sa.Column('edited_value', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('extraction_method', sa.String(length=60), nullable=True),
    sa.Column('source_document', sa.String(length=500), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('provenance_anchor_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('ikp_version', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['knowledge_review_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_review_items_batch_id'), 'knowledge_review_items', ['batch_id'], unique=False)
    op.create_index(op.f('ix_knowledge_review_items_entity_key'), 'knowledge_review_items', ['entity_key'], unique=False)
    op.create_index(op.f('ix_knowledge_review_items_entity_type'), 'knowledge_review_items', ['entity_type'], unique=False)
    op.create_index(op.f('ix_knowledge_review_items_institution_id'), 'knowledge_review_items', ['institution_id'], unique=False)
    op.create_index(op.f('ix_knowledge_review_items_status'), 'knowledge_review_items', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_review_items_status'), table_name='knowledge_review_items')
    op.drop_index(op.f('ix_knowledge_review_items_institution_id'), table_name='knowledge_review_items')
    op.drop_index(op.f('ix_knowledge_review_items_entity_type'), table_name='knowledge_review_items')
    op.drop_index(op.f('ix_knowledge_review_items_entity_key'), table_name='knowledge_review_items')
    op.drop_index(op.f('ix_knowledge_review_items_batch_id'), table_name='knowledge_review_items')
    op.drop_table('knowledge_review_items')
    op.drop_index(op.f('ix_knowledge_review_batches_institution_id'), table_name='knowledge_review_batches')
    op.drop_table('knowledge_review_batches')
    # ### end Alembic commands ###
