"""add audit evidence table

Revision ID: a1afe7223e2a
Revises: 6bcc7db53782
Create Date: 2026-06-26 09:11:58.220693+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1afe7223e2a'
down_revision: Union[str, None] = '6bcc7db53782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_evidence',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('checklist_item_id', sa.UUID(), nullable=True, comment='NULL = audit-level evidence not tied to a specific checklist item'),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=1000), nullable=False, comment='Path relative to the configured STORAGE_LOCAL_PATH root'),
    sa.Column('mime_type', sa.String(length=127), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('evidence_category', sa.String(length=80), nullable=False, comment="e.g. 'marking_guide', 'attendance_register', 'general'"),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['module_audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['audit_checklist_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_evidence_audit_id'), 'audit_evidence', ['audit_id'], unique=False)
    op.create_index(op.f('ix_audit_evidence_checklist_item_id'), 'audit_evidence', ['checklist_item_id'], unique=False)
    op.create_index(op.f('ix_audit_evidence_institution_id'), 'audit_evidence', ['institution_id'], unique=False)
    op.create_index(op.f('ix_audit_evidence_module_id'), 'audit_evidence', ['module_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_evidence_module_id'), table_name='audit_evidence')
    op.drop_index(op.f('ix_audit_evidence_institution_id'), table_name='audit_evidence')
    op.drop_index(op.f('ix_audit_evidence_checklist_item_id'), table_name='audit_evidence')
    op.drop_index(op.f('ix_audit_evidence_audit_id'), table_name='audit_evidence')
    op.drop_table('audit_evidence')
    # ### end Alembic commands ###
