"""add programme qa fields

Revision ID: bcb42a8b6462
Revises: 99c7b97c9a76
Create Date: 2026-06-24 12:30:08.667918+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcb42a8b6462'
down_revision: Union[str, None] = '99c7b97c9a76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programmes', sa.Column('qualification_type', sa.String(length=100), nullable=True, comment="e.g. 'Bachelor of Science', 'Master of Arts', 'Diploma'"))
    op.add_column('programmes', sa.Column('nqf_level', sa.Integer(), nullable=True, comment='National Qualifications Framework level (1–10)'))
    op.add_column('programmes', sa.Column('duration_years', sa.Integer(), nullable=True, comment='Nominal duration of the programme in years'))
    op.add_column('programmes', sa.Column('total_credits', sa.Integer(), nullable=True, comment='Total credits required to complete the programme'))
    op.add_column('programmes', sa.Column('status', sa.String(length=30), nullable=True, comment='Lifecycle status: active | inactive | pending_accreditation | suspended'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programmes', 'status')
    op.drop_column('programmes', 'total_credits')
    op.drop_column('programmes', 'duration_years')
    op.drop_column('programmes', 'nqf_level')
    op.drop_column('programmes', 'qualification_type')
    # ### end Alembic commands ###
