"""initial schema

Revision ID: 99c7b97c9a76
Revises: 
Create Date: 2026-06-11 14:26:32.673105+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99c7b97c9a76'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutions_code'), 'institutions', ['code'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SYSTEM_ADMIN', 'QUALITY_ASSURANCE_OFFICER', 'FACULTY_DEAN', 'HEAD_OF_DEPARTMENT', 'PROGRAMME_COORDINATOR', 'LECTURER', 'STUDENT', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_institution_id'), 'users', ['institution_id'], unique=False)
    op.create_table('faculties',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('campus', sa.String(length=100), nullable=True),
    sa.Column('dean_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dean_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'code', name='uq_faculty_institution_code')
    )
    op.create_index(op.f('ix_faculties_campus'), 'faculties', ['campus'], unique=False)
    op.create_index(op.f('ix_faculties_institution_id'), 'faculties', ['institution_id'], unique=False)
    op.create_table('departments',
    sa.Column('faculty_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('head_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['head_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faculty_id', 'code', name='uq_department_faculty_code')
    )
    op.create_index(op.f('ix_departments_faculty_id'), 'departments', ['faculty_id'], unique=False)
    op.create_table('programmes',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Enum('UNDERGRADUATE', 'POSTGRADUATE', 'DOCTORAL', name='programme_level'), nullable=False),
    sa.Column('coordinator_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coordinator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'code', name='uq_programme_department_code')
    )
    op.create_index(op.f('ix_programmes_department_id'), 'programmes', ['department_id'], unique=False)
    op.create_table('modules',
    sa.Column('programme_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=50), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('lecturer_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lecturer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('programme_id', 'code', 'academic_year', name='uq_module_programme_code_year')
    )
    op.create_index(op.f('ix_modules_programme_id'), 'modules', ['programme_id'], unique=False)
    op.create_table('audit_runs',
    sa.Column('agent_type', sa.String(length=40), nullable=False, comment='Which AI audit agent produced this run.'),
    sa.Column('module_id', sa.UUID(), nullable=True, comment='Set for module-scoped agents. NULL for programme/faculty/institution-scoped runs.'),
    sa.Column('programme_id', sa.UUID(), nullable=True, comment='Set for programme-scoped agents (e.g. Programme Review). NULL for module-scoped runs.'),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('triggered_by_id', sa.UUID(), nullable=True),
    sa.Column('run_status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('compliance_score', sa.Float(), nullable=True, comment='Weighted compliance score 0.0–100.0.'),
    sa.Column('audit_status', sa.String(length=20), nullable=True),
    sa.Column('total_required', sa.Integer(), nullable=True),
    sa.Column('documents_present', sa.Integer(), nullable=True),
    sa.Column('documents_missing', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_runs_agent_type'), 'audit_runs', ['agent_type'], unique=False)
    op.create_index(op.f('ix_audit_runs_audit_status'), 'audit_runs', ['audit_status'], unique=False)
    op.create_index(op.f('ix_audit_runs_institution_id'), 'audit_runs', ['institution_id'], unique=False)
    op.create_index(op.f('ix_audit_runs_module_id'), 'audit_runs', ['module_id'], unique=False)
    op.create_index(op.f('ix_audit_runs_programme_id'), 'audit_runs', ['programme_id'], unique=False)
    op.create_index(op.f('ix_audit_runs_run_status'), 'audit_runs', ['run_status'], unique=False)
    op.create_table('files',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=1000), nullable=False, comment='Path relative to the configured storage root.'),
    sa.Column('mime_type', sa.String(length=127), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.Enum('COURSE_OUTLINE', 'STUDY_GUIDE', 'LEARNING_OUTCOMES', 'WEEKLY_PLAN', 'ASSESSMENT_PLAN', 'ASSESSMENT_BRIEF', 'ASSESSMENT_RUBRIC', 'ASSESSMENT_MEMO', 'EXAM_PAPER', 'PRACTICAL_TASK', 'MARKED_SAMPLE', 'MARK_SHEET', 'INTERNAL_MODERATION', 'EXTERNAL_MODERATION', 'MODERATION_EVIDENCE', 'ATTENDANCE_REGISTER', 'TUTORIAL_ATTENDANCE', 'PRACTICAL_ATTENDANCE', 'LMS_PARTICIPATION', 'STUDENT_FEEDBACK', 'ACCREDITATION_EVIDENCE', 'OTHER', name='file_category'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False, comment='Latest version number. Incremented on each re-upload.'),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False, comment='SHA-256 hex digest of the file content at upload time.'),
    sa.Column('upload_state', sa.Enum('PENDING', 'SCANNING', 'READY', 'QUARANTINED', 'FAILED', name='upload_state'), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_category'), 'files', ['category'], unique=False)
    op.create_index(op.f('ix_files_institution_id'), 'files', ['institution_id'], unique=False)
    op.create_index(op.f('ix_files_is_deleted'), 'files', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_files_module_id'), 'files', ['module_id'], unique=False)
    op.create_index(op.f('ix_files_upload_state'), 'files', ['upload_state'], unique=False)
    op.create_table('audit_findings',
    sa.Column('audit_run_id', sa.UUID(), nullable=False),
    sa.Column('finding_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('document_category', sa.String(length=40), nullable=True),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_findings_audit_run_id'), 'audit_findings', ['audit_run_id'], unique=False)
    op.create_index(op.f('ix_audit_findings_document_category'), 'audit_findings', ['document_category'], unique=False)
    op.create_index(op.f('ix_audit_findings_finding_type'), 'audit_findings', ['finding_type'], unique=False)
    op.create_index(op.f('ix_audit_findings_is_resolved'), 'audit_findings', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_audit_findings_severity'), 'audit_findings', ['severity'], unique=False)
    op.create_table('document_records',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('language_detected', sa.String(length=10), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('classification', sa.String(length=40), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_records_file_id'), 'document_records', ['file_id'], unique=True)
    op.create_index(op.f('ix_document_records_institution_id'), 'document_records', ['institution_id'], unique=False)
    op.create_index(op.f('ix_document_records_status'), 'document_records', ['status'], unique=False)
    op.create_table('file_versions',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='Filename as supplied by the uploader at this version.'),
    sa.Column('stored_path', sa.String(length=1000), nullable=False, comment='Path relative to the storage root at the time of upload.'),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_versions_file_id'), 'file_versions', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_versions_file_id'), table_name='file_versions')
    op.drop_table('file_versions')
    op.drop_index(op.f('ix_document_records_status'), table_name='document_records')
    op.drop_index(op.f('ix_document_records_institution_id'), table_name='document_records')
    op.drop_index(op.f('ix_document_records_file_id'), table_name='document_records')
    op.drop_table('document_records')
    op.drop_index(op.f('ix_audit_findings_severity'), table_name='audit_findings')
    op.drop_index(op.f('ix_audit_findings_is_resolved'), table_name='audit_findings')
    op.drop_index(op.f('ix_audit_findings_finding_type'), table_name='audit_findings')
    op.drop_index(op.f('ix_audit_findings_document_category'), table_name='audit_findings')
    op.drop_index(op.f('ix_audit_findings_audit_run_id'), table_name='audit_findings')
    op.drop_table('audit_findings')
    op.drop_index(op.f('ix_files_upload_state'), table_name='files')
    op.drop_index(op.f('ix_files_module_id'), table_name='files')
    op.drop_index(op.f('ix_files_is_deleted'), table_name='files')
    op.drop_index(op.f('ix_files_institution_id'), table_name='files')
    op.drop_index(op.f('ix_files_category'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_audit_runs_run_status'), table_name='audit_runs')
    op.drop_index(op.f('ix_audit_runs_programme_id'), table_name='audit_runs')
    op.drop_index(op.f('ix_audit_runs_module_id'), table_name='audit_runs')
    op.drop_index(op.f('ix_audit_runs_institution_id'), table_name='audit_runs')
    op.drop_index(op.f('ix_audit_runs_audit_status'), table_name='audit_runs')
    op.drop_index(op.f('ix_audit_runs_agent_type'), table_name='audit_runs')
    op.drop_table('audit_runs')
    op.drop_index(op.f('ix_modules_programme_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_programmes_department_id'), table_name='programmes')
    op.drop_table('programmes')
    op.drop_index(op.f('ix_departments_faculty_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_faculties_institution_id'), table_name='faculties')
    op.drop_index(op.f('ix_faculties_campus'), table_name='faculties')
    op.drop_table('faculties')
    op.drop_index(op.f('ix_users_institution_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_institutions_code'), table_name='institutions')
    op.drop_table('institutions')
    # ### end Alembic commands ###
