"""add_adip_registry_tables

Revision ID: 7c5db84357e3
Revises: 2a7b17360d01
Create Date: 2026-06-29 13:02:40.326543+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c5db84357e3'
down_revision: Union[str, None] = '2a7b17360d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adip_documents',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('content_hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('document_category', sa.String(length=60), nullable=True),
    sa.Column('document_type', sa.String(length=60), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('processing_state', sa.String(length=30), nullable=False),
    sa.Column('registered_at', sa.String(length=50), nullable=True),
    sa.Column('registered_by', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_official_source', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adip_documents_content_hash_sha256'), 'adip_documents', ['content_hash_sha256'], unique=False)
    op.create_index(op.f('ix_adip_documents_document_type'), 'adip_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_adip_documents_institution_id'), 'adip_documents', ['institution_id'], unique=False)
    op.create_index(op.f('ix_adip_documents_processing_state'), 'adip_documents', ['processing_state'], unique=False)
    op.create_table('adip_document_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('chunk_type', sa.String(length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('slide_number', sa.Integer(), nullable=True),
    sa.Column('sheet_name', sa.String(length=100), nullable=True),
    sa.Column('cell_range', sa.String(length=50), nullable=True),
    sa.Column('section_path', sa.Text(), nullable=True),
    sa.Column('heading_level', sa.Integer(), nullable=True),
    sa.Column('char_offset_start', sa.Integer(), nullable=True),
    sa.Column('char_offset_end', sa.Integer(), nullable=True),
    sa.Column('extraction_method', sa.String(length=60), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['adip_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adip_document_chunks_document_id'), 'adip_document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_adip_document_chunks_institution_id'), 'adip_document_chunks', ['institution_id'], unique=False)
    op.create_table('adip_extraction_candidates',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('ikp_entity_type', sa.String(length=60), nullable=False),
    sa.Column('ikp_entity_key', sa.String(length=255), nullable=False),
    sa.Column('ikp_field_name', sa.String(length=100), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=False),
    sa.Column('coerced_value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('extraction_method', sa.String(length=60), nullable=False),
    sa.Column('source_verbatim', sa.Text(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reviewer_id', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['adip_document_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['adip_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adip_extraction_candidates_document_id'), 'adip_extraction_candidates', ['document_id'], unique=False)
    op.create_index(op.f('ix_adip_extraction_candidates_ikp_entity_type'), 'adip_extraction_candidates', ['ikp_entity_type'], unique=False)
    op.create_index(op.f('ix_adip_extraction_candidates_institution_id'), 'adip_extraction_candidates', ['institution_id'], unique=False)
    op.create_index(op.f('ix_adip_extraction_candidates_status'), 'adip_extraction_candidates', ['status'], unique=False)
    op.create_table('adip_provenance_anchors',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_document_title', sa.String(length=500), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('publisher_verified', sa.Boolean(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('slide_number', sa.Integer(), nullable=True),
    sa.Column('sheet_name', sa.String(length=100), nullable=True),
    sa.Column('cell_range', sa.String(length=50), nullable=True),
    sa.Column('section_path', sa.Text(), nullable=True),
    sa.Column('char_offset_start', sa.Integer(), nullable=True),
    sa.Column('char_offset_end', sa.Integer(), nullable=True),
    sa.Column('verbatim_quote', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.String(length=60), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('extractor_version', sa.String(length=60), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('confidence_breakdown', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.String(length=50), nullable=True),
    sa.Column('effective_date', sa.String(length=20), nullable=True),
    sa.Column('expiry_date', sa.String(length=20), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['adip_extraction_candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['adip_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adip_provenance_anchors_candidate_id'), 'adip_provenance_anchors', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_adip_provenance_anchors_document_id'), 'adip_provenance_anchors', ['document_id'], unique=False)
    op.create_index(op.f('ix_adip_provenance_anchors_institution_id'), 'adip_provenance_anchors', ['institution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adip_provenance_anchors_institution_id'), table_name='adip_provenance_anchors')
    op.drop_index(op.f('ix_adip_provenance_anchors_document_id'), table_name='adip_provenance_anchors')
    op.drop_index(op.f('ix_adip_provenance_anchors_candidate_id'), table_name='adip_provenance_anchors')
    op.drop_table('adip_provenance_anchors')
    op.drop_index(op.f('ix_adip_extraction_candidates_status'), table_name='adip_extraction_candidates')
    op.drop_index(op.f('ix_adip_extraction_candidates_institution_id'), table_name='adip_extraction_candidates')
    op.drop_index(op.f('ix_adip_extraction_candidates_ikp_entity_type'), table_name='adip_extraction_candidates')
    op.drop_index(op.f('ix_adip_extraction_candidates_document_id'), table_name='adip_extraction_candidates')
    op.drop_table('adip_extraction_candidates')
    op.drop_index(op.f('ix_adip_document_chunks_institution_id'), table_name='adip_document_chunks')
    op.drop_index(op.f('ix_adip_document_chunks_document_id'), table_name='adip_document_chunks')
    op.drop_table('adip_document_chunks')
    op.drop_index(op.f('ix_adip_documents_processing_state'), table_name='adip_documents')
    op.drop_index(op.f('ix_adip_documents_institution_id'), table_name='adip_documents')
    op.drop_index(op.f('ix_adip_documents_document_type'), table_name='adip_documents')
    op.drop_index(op.f('ix_adip_documents_content_hash_sha256'), table_name='adip_documents')
    op.drop_table('adip_documents')
    # ### end Alembic commands ###
