"""add_institution_domains_and_invitations

Revision ID: 4fe6f2452c07
Revises: 97b45fea2b0d
Create Date: 2026-08-05 07:38:16.627183+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fe6f2452c07'
down_revision: Union[str, None] = '97b45fea2b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('invitation_type', sa.String(length=50), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('email_restriction', sa.String(length=255), nullable=True),
    sa.Column('domain_restriction', sa.String(length=255), nullable=True),
    sa.Column('faculty_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('programme_id', sa.UUID(), nullable=True),
    sa.Column('module_id', sa.UUID(), nullable=True),
    sa.Column('permission_scope', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('requires_email_verification', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_institution_id'), 'invitations', ['institution_id'], unique=False)
    op.create_index(op.f('ix_invitations_status'), 'invitations', ['status'], unique=False)
    op.create_index(op.f('ix_invitations_token_hash'), 'invitations', ['token_hash'], unique=True)
    op.create_table('institution_domains',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_assign_student', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain', name='uq_institution_domain_domain')
    )
    op.create_index(op.f('ix_institution_domains_domain'), 'institution_domains', ['domain'], unique=False)
    op.create_index(op.f('ix_institution_domains_institution_id'), 'institution_domains', ['institution_id'], unique=False)
    # Sprint E1 tables (background_job_logs, audit_trigger_schedules, corrective_actions,
    # corrective_action_history) exist in the database but have no live ORM models;
    # they are intentionally left in place — a dedicated cleanup migration will remove
    # them once it is confirmed that no data needs to be preserved.
    op.add_column('users', sa.Column('invitation_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_invitation_id'), 'users', ['invitation_id'], unique=False)
    op.create_foreign_key(None, 'users', 'invitations', ['invitation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_invitation_id'), table_name='users')
    op.drop_column('users', 'invitation_id')
    op.drop_index(op.f('ix_institution_domains_institution_id'), table_name='institution_domains')
    op.drop_index(op.f('ix_institution_domains_domain'), table_name='institution_domains')
    op.drop_table('institution_domains')
    op.drop_index(op.f('ix_invitations_token_hash'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_status'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_institution_id'), table_name='invitations')
    op.drop_table('invitations')
