"""add module audit tables

Revision ID: 6bcc7db53782
Revises: bcb42a8b6462
Create Date: 2026-06-25 10:27:24.267047+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bcc7db53782'
down_revision: Union[str, None] = 'bcb42a8b6462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_audits',
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('programme_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('faculty_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('auditor_id', sa.UUID(), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'COMPLIANT', 'AT_RISK', 'NON_COMPLIANT', name='module_audit_status'), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('compliant_count', sa.Integer(), nullable=False),
    sa.Column('missing_count', sa.Integer(), nullable=False),
    sa.Column('partial_count', sa.Integer(), nullable=False),
    sa.Column('not_applicable_count', sa.Integer(), nullable=False),
    sa.Column('compliance_percentage', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_audits_department_id'), 'module_audits', ['department_id'], unique=False)
    op.create_index(op.f('ix_module_audits_faculty_id'), 'module_audits', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_module_audits_institution_id'), 'module_audits', ['institution_id'], unique=False)
    op.create_index(op.f('ix_module_audits_module_id'), 'module_audits', ['module_id'], unique=False)
    op.create_index(op.f('ix_module_audits_programme_id'), 'module_audits', ['programme_id'], unique=False)
    op.create_index(op.f('ix_module_audits_status'), 'module_audits', ['status'], unique=False)
    op.create_table('audit_checklist_items',
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('item_key', sa.String(length=60), nullable=False),
    sa.Column('item_label', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('COMPLIANT', 'MISSING', 'PARTIAL', 'NOT_APPLICABLE', name='checklist_item_status'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('evidence_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['module_audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', 'item_key', name='uq_checklist_audit_key')
    )
    op.create_index(op.f('ix_audit_checklist_items_audit_id'), 'audit_checklist_items', ['audit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_checklist_items_audit_id'), table_name='audit_checklist_items')
    op.drop_table('audit_checklist_items')
    op.drop_index(op.f('ix_module_audits_status'), table_name='module_audits')
    op.drop_index(op.f('ix_module_audits_programme_id'), table_name='module_audits')
    op.drop_index(op.f('ix_module_audits_module_id'), table_name='module_audits')
    op.drop_index(op.f('ix_module_audits_institution_id'), table_name='module_audits')
    op.drop_index(op.f('ix_module_audits_faculty_id'), table_name='module_audits')
    op.drop_index(op.f('ix_module_audits_department_id'), table_name='module_audits')
    op.drop_table('module_audits')
    # ### end Alembic commands ###
