"""phase_d_artifacts_actions_session_extensions

Revision ID: 7602e7b39d25
Revises: 51694630069f
Create Date: 2026-07-14 13:58:21.676002+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7602e7b39d25'
down_revision: Union[str, None] = '51694630069f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_actions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('target_entity_type', sa.String(length=64), nullable=True),
    sa.Column('target_entity_id', sa.UUID(), nullable=True),
    sa.Column('role_at_execution', sa.String(length=64), nullable=False),
    sa.Column('permission_granted', sa.Boolean(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('requires_confirmation', sa.Boolean(), nullable=False),
    sa.Column('confirmation_received', sa.Boolean(), nullable=False),
    sa.Column('proposed_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('audit_log_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_chat_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_actions_action_type'), 'ai_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_ai_actions_institution_id'), 'ai_actions', ['institution_id'], unique=False)
    op.create_index(op.f('ix_ai_actions_session_id'), 'ai_actions', ['session_id'], unique=False)
    op.create_index(op.f('ix_ai_actions_user_id'), 'ai_actions', ['user_id'], unique=False)
    op.create_table('ai_artifacts',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rendered_content', sa.Text(), nullable=True),
    sa.Column('source_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_frameworks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_assessments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('parent_artifact_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approval_status', sa.String(length=32), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.String(length=32), nullable=True),
    sa.Column('export_formats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_exported_at', sa.String(length=32), nullable=True),
    sa.Column('last_exported_format', sa.String(length=16), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_chat_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['ai_chat_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_artifact_id'], ['ai_artifacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_artifacts_artifact_type'), 'ai_artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_ai_artifacts_conversation_id'), 'ai_artifacts', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_artifacts_created_by'), 'ai_artifacts', ['created_by'], unique=False)
    op.create_index(op.f('ix_ai_artifacts_institution_id'), 'ai_artifacts', ['institution_id'], unique=False)
    op.create_index(op.f('ix_ai_artifacts_tenant_id'), 'ai_artifacts', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_qualification_records_user_id'), table_name='qualification_records')
    op.drop_table('qualification_records')
    op.add_column('ai_chat_messages', sa.Column('structured_blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ai_chat_messages', sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ai_chat_messages', sa.Column('action_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ai_chat_messages', sa.Column('referenced_evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ai_chat_messages', sa.Column('referenced_finding_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ai_chat_messages', sa.Column('referenced_framework_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ai_chat_messages', sa.Column('referenced_assessment_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ai_chat_messages', sa.Column('artifact_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ai_chat_messages', sa.Column('attached_file_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ai_chat_sessions', sa.Column('is_pinned', sa.Boolean(), nullable=False))
    op.add_column('ai_chat_sessions', sa.Column('is_archived', sa.Boolean(), nullable=False))
    op.add_column('ai_chat_sessions', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('ai_chat_sessions', sa.Column('module_id', sa.UUID(), nullable=True))
    op.add_column('ai_chat_sessions', sa.Column('programme_id', sa.UUID(), nullable=True))
    op.add_column('ai_chat_sessions', sa.Column('department_id', sa.UUID(), nullable=True))
    op.add_column('ai_chat_sessions', sa.Column('faculty_id', sa.UUID(), nullable=True))
    op.add_column('ai_chat_sessions', sa.Column('academic_year', sa.String(length=16), nullable=True))
    op.add_column('ai_chat_sessions', sa.Column('semester', sa.String(length=8), nullable=True))
    op.add_column('ai_chat_sessions', sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_ai_chat_sessions_institution_id'), 'ai_chat_sessions', ['institution_id'], unique=False)
    op.drop_index(op.f('ix_cross_framework_mappings_version_a'), table_name='cross_framework_mappings')
    op.drop_index(op.f('ix_cross_framework_mappings_version_b'), table_name='cross_framework_mappings')
    op.create_index(op.f('ix_cross_framework_mappings_framework_version_a_id'), 'cross_framework_mappings', ['framework_version_a_id'], unique=False)
    op.create_index(op.f('ix_cross_framework_mappings_framework_version_b_id'), 'cross_framework_mappings', ['framework_version_b_id'], unique=False)
    op.drop_constraint(op.f('uq_regulatory_authorities_code'), 'regulatory_authorities', type_='unique')
    op.drop_index(op.f('ix_regulatory_authorities_code'), table_name='regulatory_authorities')
    op.create_index(op.f('ix_regulatory_authorities_code'), 'regulatory_authorities', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regulatory_authorities_code'), table_name='regulatory_authorities')
    op.create_index(op.f('ix_regulatory_authorities_code'), 'regulatory_authorities', ['code'], unique=False)
    op.create_unique_constraint(op.f('uq_regulatory_authorities_code'), 'regulatory_authorities', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_cross_framework_mappings_framework_version_b_id'), table_name='cross_framework_mappings')
    op.drop_index(op.f('ix_cross_framework_mappings_framework_version_a_id'), table_name='cross_framework_mappings')
    op.create_index(op.f('ix_cross_framework_mappings_version_b'), 'cross_framework_mappings', ['framework_version_b_id'], unique=False)
    op.create_index(op.f('ix_cross_framework_mappings_version_a'), 'cross_framework_mappings', ['framework_version_a_id'], unique=False)
    op.drop_index(op.f('ix_ai_chat_sessions_institution_id'), table_name='ai_chat_sessions')
    op.drop_column('ai_chat_sessions', 'context_snapshot')
    op.drop_column('ai_chat_sessions', 'semester')
    op.drop_column('ai_chat_sessions', 'academic_year')
    op.drop_column('ai_chat_sessions', 'faculty_id')
    op.drop_column('ai_chat_sessions', 'department_id')
    op.drop_column('ai_chat_sessions', 'programme_id')
    op.drop_column('ai_chat_sessions', 'module_id')
    op.drop_column('ai_chat_sessions', 'is_deleted')
    op.drop_column('ai_chat_sessions', 'is_archived')
    op.drop_column('ai_chat_sessions', 'is_pinned')
    op.drop_column('ai_chat_messages', 'attached_file_ids')
    op.drop_column('ai_chat_messages', 'artifact_ids')
    op.drop_column('ai_chat_messages', 'referenced_assessment_ids')
    op.drop_column('ai_chat_messages', 'referenced_framework_ids')
    op.drop_column('ai_chat_messages', 'referenced_finding_ids')
    op.drop_column('ai_chat_messages', 'referenced_evidence_ids')
    op.drop_column('ai_chat_messages', 'action_results')
    op.drop_column('ai_chat_messages', 'citations')
    op.drop_column('ai_chat_messages', 'structured_blocks')
    op.create_table('qualification_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('institution_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('programme_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('qualification_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nqf_level_claimed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('academic_year', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('total_credits', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('gpa', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('cgpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('nqf_advisory_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nqf_advisory_label', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('entries', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('calculation_result', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('qualification_records_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('qualification_records_pkey'))
    )
    op.create_index(op.f('ix_qualification_records_user_id'), 'qualification_records', ['user_id'], unique=False)
    op.drop_index(op.f('ix_ai_artifacts_tenant_id'), table_name='ai_artifacts')
    op.drop_index(op.f('ix_ai_artifacts_institution_id'), table_name='ai_artifacts')
    op.drop_index(op.f('ix_ai_artifacts_created_by'), table_name='ai_artifacts')
    op.drop_index(op.f('ix_ai_artifacts_conversation_id'), table_name='ai_artifacts')
    op.drop_index(op.f('ix_ai_artifacts_artifact_type'), table_name='ai_artifacts')
    op.drop_table('ai_artifacts')
    op.drop_index(op.f('ix_ai_actions_user_id'), table_name='ai_actions')
    op.drop_index(op.f('ix_ai_actions_session_id'), table_name='ai_actions')
    op.drop_index(op.f('ix_ai_actions_institution_id'), table_name='ai_actions')
    op.drop_index(op.f('ix_ai_actions_action_type'), table_name='ai_actions')
    op.drop_table('ai_actions')
    # ### end Alembic commands ###
