"""Qualification Intelligence API routes.

Endpoints
---------
POST /qualification-intelligence/calculate       Stateless GPA/CGPA/advisory calculation
POST /qualification-intelligence/records         Save a calculation result
GET  /qualification-intelligence/records         List user's saved records
GET  /qualification-intelligence/records/{id}    Retrieve a specific record
DELETE /qualification-intelligence/records/{id}  Delete a record
GET  /qualification-intelligence/records/{id}/export/csv  CSV export

All endpoints are available to any authenticated staff member.
Records are scoped to the requesting user — users cannot see each other's records.

Advisory disclaimer
-------------------
All outputs are advisory only. They do NOT constitute official SAQA evaluations.
"""

from __future__ import annotations

import csv
import io
import uuid

from fastapi import APIRouter, Depends, status
from fastapi.responses import Response
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.dependencies import AnyAuthenticatedUser
from app.models.user import User
from app.schemas.qualification import (
    CalculationRequest,
    CalculationResult,
    QualificationRecordBrief,
    QualificationRecordCreate,
    QualificationRecordDetail,
)
from app.services import qualification_service

router = APIRouter(prefix="/qualification-intelligence", tags=["Qualification Intelligence"])

_DISCLAIMER = (
    "ADVISORY ONLY — This output was generated by the AQAA Qualification Intelligence tool "
    "for internal advisory purposes. It does NOT constitute an official SAQA qualification "
    "evaluation, recognition of prior learning determination, or any formal academic credential "
    "assessment. Contact SAQA or the relevant Quality Council for official evaluations."
)


# ---------------------------------------------------------------------------
# Stateless calculation
# ---------------------------------------------------------------------------


@router.post(
    "/calculate",
    response_model=CalculationResult,
    summary="Stateless GPA/CGPA/NQF advisory calculation",
    description=_DISCLAIMER,
)
async def calculate(
    payload: CalculationRequest,
    _user: User = AnyAuthenticatedUser,
) -> CalculationResult:
    """Compute GPA, CGPA, and advisory NQF mapping without persisting to the database."""
    return qualification_service.compute(payload)


# ---------------------------------------------------------------------------
# Persisted records
# ---------------------------------------------------------------------------


@router.post(
    "/records",
    response_model=QualificationRecordBrief,
    status_code=status.HTTP_201_CREATED,
    summary="Save a qualification calculation to the database",
)
async def save_record(
    payload: QualificationRecordCreate,
    db: AsyncSession = Depends(get_db),
    user: User = AnyAuthenticatedUser,
) -> QualificationRecordBrief:
    result = qualification_service.compute(payload)
    record = await qualification_service.save_record(db, user, payload, result)
    return QualificationRecordBrief.model_validate(record)


@router.get(
    "/records",
    response_model=list[QualificationRecordBrief],
    summary="List the current user's saved qualification records",
)
async def list_records(
    limit: int = 50,
    offset: int = 0,
    db: AsyncSession = Depends(get_db),
    user: User = AnyAuthenticatedUser,
) -> list[QualificationRecordBrief]:
    records = await qualification_service.list_records(db, user, limit=limit, offset=offset)
    return [QualificationRecordBrief.model_validate(r) for r in records]


@router.get(
    "/records/{record_id}",
    response_model=QualificationRecordDetail,
    summary="Retrieve a specific qualification record",
)
async def get_record(
    record_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    user: User = AnyAuthenticatedUser,
) -> QualificationRecordDetail:
    record = await qualification_service.get_record(db, record_id, user)
    return QualificationRecordDetail.model_validate(record)


@router.delete(
    "/records/{record_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete a qualification record",
)
async def delete_record(
    record_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    user: User = AnyAuthenticatedUser,
) -> None:
    await qualification_service.delete_record(db, record_id, user)


@router.get(
    "/records/{record_id}/export/csv",
    summary="Export a qualification record as CSV",
    response_class=Response,
)
async def export_csv(
    record_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    user: User = AnyAuthenticatedUser,
) -> Response:
    """Download the subject breakdown and advisory summary as a CSV file."""
    record = await qualification_service.get_record(db, record_id, user)
    calc = record.calculation_result

    buf = io.StringIO()
    writer = csv.writer(buf)

    # Header block
    writer.writerow(["AQAA Qualification Intelligence — Advisory Report"])
    writer.writerow(["ADVISORY ONLY — Not an official SAQA evaluation"])
    writer.writerow([])
    writer.writerow(["Student", record.student_name])
    writer.writerow(["Institution", record.institution_name])
    writer.writerow(["Programme", record.programme_name])
    writer.writerow(["Qualification Type", record.qualification_type])
    writer.writerow(["Academic Year", record.academic_year or ""])
    writer.writerow(["GPA", f"{record.gpa:.2f}"])
    writer.writerow(["CGPA", f"{record.cgpa:.2f}" if record.cgpa is not None else ""])
    writer.writerow(["Total Credits", f"{record.total_credits:.0f}"])
    writer.writerow(["Advisory NQF Level", record.nqf_advisory_level or ""])
    writer.writerow(["Advisory NQF Label", record.nqf_advisory_label or ""])
    writer.writerow([])

    # Subject breakdown
    writer.writerow(["Subject", "Credits", "Percentage", "Grade", "Grade Points", "Quality Points", "Semester", "Passed"])
    for s in calc.get("subjects", []):
        writer.writerow([
            s.get("name"),
            s.get("credits"),
            s.get("percentage"),
            s.get("letter_grade"),
            s.get("grade_points"),
            s.get("quality_points"),
            s.get("semester"),
            "Yes" if s.get("passed") else "No",
        ])

    writer.writerow([])
    writer.writerow(["Advisory Summary"])
    writer.writerow([calc.get("advisory_summary", "")])
    writer.writerow([])
    writer.writerow(["Warnings"])
    for w in calc.get("advisory_warnings", []):
        writer.writerow([w])
    writer.writerow([])
    writer.writerow(["Recommendations"])
    for r in calc.get("advisory_recommendations", []):
        writer.writerow([r])
    writer.writerow([])
    writer.writerow([_DISCLAIMER])

    csv_bytes = ("﻿" + buf.getvalue()).encode("utf-8")
    return Response(
        content=csv_bytes,
        media_type="text/csv",
        headers={
            "Content-Disposition": (
                f'attachment; filename="qualification_advisory_{record_id}.csv"'
            )
        },
    )
