"""Pydantic schemas for the Qualification Intelligence subsystem."""

from __future__ import annotations

import uuid
from datetime import datetime

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# Subject entry (one row in a transcript)
# ---------------------------------------------------------------------------


class SubjectEntry(BaseModel):
    """One subject/module on a transcript."""

    name: str = Field(..., min_length=1, max_length=255, description="Subject or module name")
    credits: float = Field(..., gt=0, le=240, description="Credit value of this subject")
    percentage: float = Field(..., ge=0, le=100, description="Mark as a percentage")
    semester: int = Field(default=1, ge=1, le=12, description="Semester number (used for CGPA grouping)")


# ---------------------------------------------------------------------------
# Calculation request / response (stateless — no DB write)
# ---------------------------------------------------------------------------


class CalculationRequest(BaseModel):
    """Stateless GPA/CGPA/advisory calculation request."""

    student_name: str = Field(default="", max_length=255)
    institution_name: str = Field(default="", max_length=255)
    programme_name: str = Field(default="", max_length=255)
    qualification_type: str = Field(
        default="bachelor",
        description="Type: certificate | diploma | bachelor | honours | masters | doctoral",
    )
    nqf_level_claimed: int | None = Field(default=None, ge=5, le=10)
    academic_year: str | None = Field(default=None, max_length=20)
    entries: list[SubjectEntry] = Field(..., min_length=1)
    notes: str | None = Field(default=None, max_length=2000)

    @field_validator("entries")
    @classmethod
    def at_least_one_entry(cls, v: list[SubjectEntry]) -> list[SubjectEntry]:
        if not v:
            raise ValueError("At least one subject entry is required.")
        return v


class SubjectResult(BaseModel):
    """Calculated result for one subject entry."""

    name: str
    credits: float
    percentage: float
    letter_grade: str
    grade_points: float
    quality_points: float
    semester: int
    passed: bool


class SemesterGPA(BaseModel):
    """GPA and credits for one semester."""

    semester: int
    gpa: float
    credits: float
    subjects: int


class NQFAdvisory(BaseModel):
    """Advisory NQF level mapping — clearly advisory, not official SAQA determination."""

    advisory_level: int
    advisory_label: str
    qualification_type_advisory: str
    minimum_credits: int
    actual_credits: float
    credit_gap: float
    advisory_note: str


class CalculationResult(BaseModel):
    """Full advisory qualification calculation result."""

    student_name: str
    institution_name: str
    programme_name: str
    qualification_type: str
    academic_year: str | None

    # Subject breakdown
    subjects: list[SubjectResult]

    # Aggregates
    total_credits: float
    total_quality_points: float
    gpa: float
    cgpa: float
    passed_subjects: int
    failed_subjects: int
    pass_rate: float

    # Semester breakdown
    semesters: list[SemesterGPA]

    # NQF advisory
    nqf_advisory: NQFAdvisory

    # Advisory report
    advisory_summary: str
    advisory_warnings: list[str]
    advisory_recommendations: list[str]

    disclaimer: str = (
        "ADVISORY ONLY — This report is generated by the AQAA Qualification Intelligence "
        "tool for internal advisory purposes. It does NOT constitute an official SAQA "
        "qualification evaluation, recognition of prior learning determination, or any "
        "formal academic credential assessment. Contact SAQA or the relevant Quality "
        "Council for official evaluations."
    )


# ---------------------------------------------------------------------------
# Save / retrieve records (persisted to DB)
# ---------------------------------------------------------------------------


class QualificationRecordCreate(CalculationRequest):
    """Save a calculation result to the database."""


class QualificationRecordBrief(BaseModel):
    """Summary row for list views."""

    id: uuid.UUID
    student_name: str
    institution_name: str
    programme_name: str
    qualification_type: str
    academic_year: str | None
    total_credits: float
    gpa: float
    cgpa: float | None
    nqf_advisory_level: int | None
    nqf_advisory_label: str | None
    created_at: datetime

    model_config = {"from_attributes": True}


class QualificationRecordDetail(QualificationRecordBrief):
    """Full record including entries and calculation result."""

    entries: list[dict]
    calculation_result: dict
    notes: str | None

    model_config = {"from_attributes": True}
